project:
  name: "YiYuTongSheng"
  target_language: "en"
  sample_rate: 44100

paths:
  opencpop_midi: "data/dataset/opencpop/midis/2001.midi"
  opencpop_textgrid: "data/dataset/opencpop/textgrids/2001.TextGrid"

  lyrics_zh: "data/lyrics/lyrics_zh.txt"
  phrase_map: "data/lyrics/phrase_map.json"

  melody_midi: "data/score/melody.mid"
  melody_notes: "data/score/melody_notes.json"

  lyrics_literal: "data/lyrics/lyrics_literal.json"
  lyrics_singable: "data/lyrics/lyrics_singable.json"
  lyrics_singable_manual: "data/lyrics/lyrics_singable_manual.json"

  phonemes_target: "data/phoneme/phonemes_target.json"
  note_lyric_alignment: "data/alignment/note_lyric_alignment.json"
  dtw_syllable_alignment: "data/alignment/dtw_syllable_alignment.json"

  svs_vocal_flat: "data/svs/target_language_vocal_flat.wav"
  svs_vocal: "data/svs/target_language_vocal.wav"

opencpop:
  sample_id: '2001'

svs:
  backend: "melotts_aligned_dtw_world"
  melotts_language: "EN"
  melotts_speaker: "EN-US"
  melotts_speed: 0.85
  device: "auto"

  phrase_fade_ms: 20
  normalize_peak: 0.98
  enable_phrase_pitch_shift: false
  flat_vocal: "data/svs/target_language_vocal_flat.wav"

  enable_world_f0: true
  world_frame_period: 5.0
  f0_smooth_window: 5

  enable_aligned_dtw: true
  dtw_feature: "rms"
  dtw_band_rad: 0.25
  dtw_energy_frames_per_second: 200

  enable_vibrato: true
  vibrato_rate: 5.5
  vibrato_depth: 0.006
  min_vibrato_note_duration: 0.45

  midi_transpose: 0

pipeline:
  allow_mock_outputs: false
  overwrite: true

models:
  translation_backend: "qwen_api"
  translation_model: "qwen3.6-plus"
  translation_batch_size: 12
  qwen_base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
