from __future__ import annotations

import argparse
import gc
import json
import os
import re
import sys
from pathlib import Path


def _patch_numpy_aliases() -> None:
    try:
        import numpy as np
    except ImportError:
        return
    for name, value in {
        "int": int,
        "float": float,
        "bool": bool,
        "complex": complex,
        "object": object,
    }.items():
        if not hasattr(np, name):
            setattr(np, name, value)


def _patch_yaml_open_encoding() -> None:
    import builtins

    original_open = builtins.open

    def open_with_utf8_yaml(file, mode="r", buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None):
        if encoding is None and "b" not in mode:
            path_text = os.fspath(file) if isinstance(file, (str, os.PathLike)) else ""
            if path_text.lower().endswith((".yaml", ".yml")):
                encoding = "utf-8"
        return original_open(file, mode, buffering, encoding, errors, newline, closefd, opener)

    builtins.open = open_with_utf8_yaml


def _patch_scipy_signal_aliases() -> None:
    try:
        import scipy.signal as signal
        from scipy.signal import windows
    except ImportError:
        return
    if not hasattr(signal, "kaiser") and hasattr(windows, "kaiser"):
        signal.kaiser = windows.kaiser


def _install_optional_training_stubs() -> None:
    try:
        import webrtcvad  # noqa: F401
        return
    except ImportError:
        pass

    import types

    module = types.ModuleType("webrtcvad")

    class _Vad:
        def __init__(self, *_args, **_kwargs):
            raise RuntimeError("webrtcvad is not installed; VAD trimming is unavailable during training/data preparation.")

    module.Vad = _Vad
    sys.modules["webrtcvad"] = module


def _install_pypinyin_stub() -> None:
    try:
        import pypinyin  # noqa: F401
        return
    except ImportError:
        pass

    import types

    module = types.ModuleType("pypinyin")

    class _Style:
        NORMAL = 0
        TONE3 = 8

    def _missing_pypinyin(*_args, **_kwargs):
        raise RuntimeError(
            "pypinyin is not installed. Word-level DiffSinger input is unavailable, "
            "but phoneme-level OpenCpop input does not require it."
        )

    module.Style = _Style
    module.lazy_pinyin = _missing_pypinyin
    module.pinyin = _missing_pypinyin
    sys.modules["pypinyin"] = module


def _install_diffsinger_task_stub() -> None:
    if "usr.diffsinger_task" in sys.modules:
        return

    import types
    from usr.diff.candidate_decoder import FFT
    from usr.diff.net import DiffNet

    module = types.ModuleType("usr.diffsinger_task")
    module.DIFF_DECODERS = {
        "wavenet": lambda hp: DiffNet(hp["audio_num_mel_bins"]),
        "fft": lambda hp: FFT(hp["hidden_size"], hp["dec_layers"], hp["dec_ffn_kernel_size"], hp["num_heads"]),
    }
    sys.modules["usr.diffsinger_task"] = module


def _load_infer_class(name: str):
    value = name.lower().strip()
    if value in {"e2e", "ds_e2e", "diffsinger_e2e"}:
        from inference.svs.ds_e2e import DiffSingerE2EInfer
        return DiffSingerE2EInfer
    if value in {"cascade", "ds_cascade", "diffsinger_cascade"}:
        from inference.svs.ds_cascade import DiffSingerCascadeInfer
        return DiffSingerCascadeInfer
    raise ValueError(f"Unsupported DiffSinger infer class: {name}")

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run DiffSinger OpenCpop inference from phrase-level JSON input.")
    parser.add_argument("--diffsinger-root", required=True, help="Path to external DiffSinger source root.")
    parser.add_argument("--config", required=True, help="DiffSinger config YAML path, relative to DiffSinger root or absolute.")
    parser.add_argument("--exp-name", required=True, help="DiffSinger checkpoint experiment name under checkpoints/.")
    parser.add_argument("--input-json", required=True, help="Input JSON generated by src.svs.diffsinger_opencpop_exporter.")
    parser.add_argument("--output-wav", required=True, help="Destination wav path.")
    parser.add_argument("--infer-class", default="cascade", help="e2e or cascade. OpenCpop release checkpoints are usually cascade-family.")
    parser.add_argument("--device", default="auto", help="auto, cpu, cuda, or cuda:N.")
    parser.add_argument("--hparams", default="", help="Optional comma-separated DiffSinger hparams overrides.")
    parser.add_argument("--normalize", action="store_true", help="Peak-normalize saved wav.")
    parser.add_argument("--segments-dir", default="", help="Directory for phrase-level wav segments.")
    parser.add_argument("--max-phrases", type=int, default=None, help="Maximum number of phrases to infer.")
    parser.add_argument("--start-phrase", type=int, default=1, help="1-based phrase offset for low-memory tests/resume.")
    parser.add_argument("--assembly-mode", default="timeline", choices=["timeline", "concat"], help="How to assemble phrase wavs.")
    parser.add_argument("--f0-fallback-config", default="", help="JSON config for notes-based f0 fallback naturalization.")
    return parser.parse_args()


def _load_payloads(input_json: Path) -> tuple[list[dict], str]:
    payload = json.loads(input_json.read_text(encoding="utf-8"))
    if isinstance(payload, dict) and isinstance(payload.get("diffsinger_inputs"), list):
        return [item for item in payload["diffsinger_inputs"] if isinstance(item, dict)], "diffsinger_inputs"
    if isinstance(payload, dict):
        return [payload], "diffsinger_input"
    raise ValueError(f"Unsupported DiffSinger input JSON format: {input_json}")


def _validate_payload(payload: dict, index: int) -> None:
    input_type = str(payload.get("input_type") or "word").strip().lower()
    if input_type == "word":
        required = ["text", "notes", "notes_duration", "input_type"]
    elif input_type == "phoneme":
        required = ["text", "ph_seq", "note_seq", "note_dur_seq", "is_slur_seq", "input_type"]
    else:
        name = payload.get("item_name") or f"phrase_{index}"
        raise ValueError(f"DiffSinger input {name} has unsupported input_type: {input_type!r}")

    missing = [key for key in required if not payload.get(key)]
    if missing:
        name = payload.get("item_name") or f"phrase_{index}"
        raise ValueError(f"DiffSinger input {name} missing required fields: {missing}")


def _has_word_level_payload(payloads: list[dict]) -> bool:
    return any(str(payload.get("input_type") or "word").strip().lower() == "word" for payload in payloads)


def _ensure_real_pypinyin_available() -> None:
    try:
        import pypinyin  # noqa: F401
    except ImportError as exc:
        raise RuntimeError(
            "Word-level DiffSinger input requires pypinyin. Please run:\n"
            "python -m pip install pypinyin"
        ) from exc


def _select_payloads(payloads: list[dict], start_phrase: int, max_phrases: int | None) -> list[dict]:
    start_index = max(start_phrase, 1) - 1
    selected = payloads[start_index:]
    if max_phrases is not None and max_phrases > 0:
        selected = selected[:max_phrases]
    return selected


def _cleanup_cuda() -> None:
    gc.collect()
    try:
        import torch
    except ImportError:
        return
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def _read_wav(path: Path) -> tuple[object, int]:
    try:
        import soundfile as sf
        wav, sample_rate = sf.read(str(path), dtype="float32")
        return wav, int(sample_rate)
    except ImportError:
        from scipy.io import wavfile
        sample_rate, wav = wavfile.read(str(path))
        import numpy as np
        if wav.dtype.kind in {"i", "u"}:
            max_value = float(np.iinfo(wav.dtype).max)
            wav = wav.astype("float32") / max_value
        else:
            wav = wav.astype("float32")
        return wav, int(sample_rate)


def _to_mono(wav):
    if getattr(wav, "ndim", 1) == 2:
        return wav.mean(axis=1)
    return wav


NOTE_OFFSETS = {
    "C": 0,
    "D": 2,
    "E": 4,
    "F": 5,
    "G": 7,
    "A": 9,
    "B": 11,
}


DEFAULT_F0_FALLBACK_CONFIG = {
    "enabled": True,
    "naturalize": True,
    "transition_ms": 50,
    "vibrato_enabled": True,
    "vibrato_threshold_sec": 0.35,
    "vibrato_rate_hz": 5.5,
    "vibrato_depth_cents": 15,
    "vibrato_delay_sec": 0.15,
    "vibrato_fade_sec": 0.08,
    "tail_fall_enabled": True,
    "tail_fall_ms": 150,
    "tail_fall_cents": 20,
    "jitter_enabled": True,
    "jitter_cents": 2,
    "random_seed": 1234,
}


def _load_f0_fallback_config(raw: str | dict | None) -> dict:
    config = dict(DEFAULT_F0_FALLBACK_CONFIG)
    if isinstance(raw, dict):
        config.update(raw)
        return config
    if not raw:
        return config
    payload = json.loads(raw)
    if not isinstance(payload, dict):
        raise ValueError("--f0-fallback-config must decode to a JSON object.")
    config.update(payload)
    return config


def _note_to_hz(note: str) -> float:
    value = str(note or "").strip()
    if "/" in value:
        value = value.split("/", 1)[0].strip()
    if not value or value.upper() in {"AP", "SP"} or value.lower() == "rest":
        return 0.0

    match = re.match(r"^([A-Ga-g])([#b]?)(-?\d+)$", value)
    if match is None:
        raise ValueError(f"Unsupported note name for f0 fallback: {note!r}")

    name, accidental, octave_text = match.groups()
    midi = (int(octave_text) + 1) * 12 + NOTE_OFFSETS[name.upper()]
    if accidental == "#":
        midi += 1
    elif accidental == "b":
        midi -= 1
    return 440.0 * (2.0 ** ((midi - 69) / 12.0))


def _split_grouped_values(text: str) -> list[str]:
    values: list[str] = []
    for group in str(text or "").split("|"):
        values.extend(part.strip() for part in group.split() if part.strip())
    return values


def _parse_payload_notes_and_durations(payload: dict) -> tuple[list[str], list[float]]:
    item_name = payload.get("item_name", "<unknown>")
    notes = _split_grouped_values(str(payload.get("notes", "")))
    duration_values = _split_grouped_values(str(payload.get("notes_duration", "")))
    if len(notes) != len(duration_values):
        raise ValueError(
            f"Cannot build f0 fallback for {item_name}: "
            f"note_count={len(notes)}, duration_count={len(duration_values)}."
        )
    try:
        durations = [max(float(value), 0.0) for value in duration_values]
    except ValueError as exc:
        raise ValueError(f"Cannot build f0 fallback for {item_name}: invalid notes_duration.") from exc
    return notes, durations


def _build_step_f0_from_payload_notes(payload: dict, mel_out, hp: dict):
    import numpy as np

    notes, durations = _parse_payload_notes_and_durations(payload)
    frames = int(mel_out.shape[1] if len(mel_out.shape) >= 3 else mel_out.shape[-2])
    sample_rate = int(hp["audio_sample_rate"])
    hop_size = int(hp["hop_size"])

    f0_values: list[float] = []
    note_events: list[dict] = []
    note_hz_values = [_note_to_hz(note) for note in notes]
    for note, hz, duration in zip(notes, note_hz_values, durations):
        start_frame = len(f0_values)
        frame_count = max(1, int(round(duration * sample_rate / hop_size)))
        f0_values.extend([hz] * frame_count)
        note_events.append(
            {
                "note": note,
                "hz": float(hz),
                "duration": float(duration),
                "start_frame": int(start_frame),
                "end_frame": int(start_frame + frame_count),
                "is_rest": bool(hz <= 0.0),
            }
        )

    if not f0_values:
        raise ValueError(f"Cannot build f0 fallback for {payload.get('item_name', '<unknown>')}: empty note list.")

    if len(f0_values) < frames:
        f0_values.extend([f0_values[-1] if f0_values else 0.0] * (frames - len(f0_values)))
    elif len(f0_values) > frames:
        f0_values = f0_values[:frames]

    for event in note_events:
        event["start_frame"] = min(int(event["start_frame"]), frames)
        event["end_frame"] = min(int(event["end_frame"]), frames)

    non_rest_hz = [hz for hz in note_hz_values if hz > 0.0]
    if non_rest_hz and max(f0_values) <= 0.0:
        raise ValueError(f"Cannot build f0 fallback for {payload.get('item_name', '<unknown>')}: all generated f0 is zero.")

    return np.asarray(f0_values, dtype=np.float32), note_events


def _naturalize_f0_from_notes(f0_raw, note_events: list[dict], hp: dict, config: dict):
    import numpy as np

    f0 = np.asarray(f0_raw, dtype=np.float32).copy()
    if f0.size == 0 or not bool(config.get("naturalize", True)):
        return f0

    sample_rate = int(hp["audio_sample_rate"])
    hop_size = int(hp["hop_size"])
    fps = sample_rate / float(hop_size)

    transition_frames = max(1, int(round(float(config.get("transition_ms", 50)) / 1000.0 * fps)))
    for prev_event, next_event in zip(note_events, note_events[1:]):
        if prev_event.get("is_rest") or next_event.get("is_rest"):
            continue
        prev_start = int(prev_event["start_frame"])
        prev_end = int(prev_event["end_frame"])
        next_start = int(next_event["start_frame"])
        next_end = int(next_event["end_frame"])
        if prev_end <= prev_start or next_end <= next_start:
            continue
        half_window = min(transition_frames // 2, (prev_end - prev_start) // 2, (next_end - next_start) // 2)
        if half_window <= 0:
            continue
        start = max(prev_start, prev_end - half_window)
        end = min(next_end, next_start + half_window)
        if end <= start:
            continue
        prev_hz = float(prev_event["hz"])
        next_hz = float(next_event["hz"])
        steps = end - start
        alpha = 0.5 - 0.5 * np.cos(np.linspace(0.0, np.pi, steps, dtype=np.float32))
        f0[start:end] = prev_hz * (1.0 - alpha) + next_hz * alpha

    if bool(config.get("vibrato_enabled", True)):
        threshold = float(config.get("vibrato_threshold_sec", 0.35))
        rate = float(config.get("vibrato_rate_hz", 5.5))
        depth_cents = float(config.get("vibrato_depth_cents", 15))
        delay = float(config.get("vibrato_delay_sec", 0.15))
        fade = max(float(config.get("vibrato_fade_sec", 0.08)), 0.001)
        depth_ratio = 2.0 ** (depth_cents / 1200.0) - 1.0
        for event in note_events:
            if event.get("is_rest") or float(event.get("duration", 0.0)) < threshold:
                continue
            start = int(event["start_frame"])
            end = int(event["end_frame"])
            if end <= start:
                continue
            frame_indices = np.arange(end - start, dtype=np.float32)
            t = frame_indices / fps
            envelope = np.clip((t - delay) / fade, 0.0, 1.0)
            tail = np.clip((float(event["duration"]) - t) / fade, 0.0, 1.0)
            envelope = np.minimum(envelope, tail)
            vibrato = np.sin(2.0 * np.pi * rate * t) * depth_ratio * envelope
            voiced = f0[start:end] > 0.0
            segment = f0[start:end]
            segment[voiced] *= (1.0 + vibrato[voiced]).astype(np.float32)
            f0[start:end] = segment

    if bool(config.get("tail_fall_enabled", True)):
        voiced_events = [event for event in note_events if not event.get("is_rest") and float(event.get("duration", 0.0)) > 0.25]
        if voiced_events:
            event = voiced_events[-1]
            end = int(event["end_frame"])
            start = int(event["start_frame"])
            fall_frames = int(round(float(config.get("tail_fall_ms", 150)) / 1000.0 * fps))
            fall_frames = min(max(fall_frames, 1), max((end - start) // 2, 1))
            fall_start = max(start, end - fall_frames)
            cents = float(config.get("tail_fall_cents", 20))
            ratios = 2.0 ** (-(np.linspace(0.0, cents, end - fall_start, dtype=np.float32)) / 1200.0)
            voiced = f0[fall_start:end] > 0.0
            segment = f0[fall_start:end]
            segment[voiced] *= ratios[voiced]
            f0[fall_start:end] = segment

    if bool(config.get("jitter_enabled", True)) and float(config.get("jitter_cents", 2)) > 0.0:
        rng = np.random.default_rng(int(config.get("random_seed", 1234)))
        control_count = max(4, int(np.ceil(f0.size / max(fps * 0.12, 1.0))) + 1)
        control_x = np.linspace(0, f0.size - 1, control_count)
        noise = rng.normal(0.0, 1.0, size=control_count)
        frame_x = np.arange(f0.size)
        smooth_noise = np.interp(frame_x, control_x, noise)
        jitter = 2.0 ** ((smooth_noise * float(config.get("jitter_cents", 2))) / 1200.0)
        voiced = f0 > 0.0
        f0[voiced] *= jitter[voiced].astype(np.float32)

    f0[~np.isfinite(f0)] = 0.0
    f0[np.asarray(f0_raw) <= 0.0] = 0.0
    return f0.astype(np.float32)


def _build_f0_from_payload_notes(payload: dict, mel_out, hp: dict, config: dict):
    import torch

    if not bool(config.get("enabled", True)):
        return None, None
    f0_raw, note_events = _build_step_f0_from_payload_notes(payload, mel_out, hp)
    f0_natural = _naturalize_f0_from_notes(f0_raw, note_events, hp, config)
    f0_tensor = torch.tensor(f0_natural, dtype=torch.float32, device=mel_out.device)[None, :]
    return f0_tensor, {
        "f0_raw": f0_raw,
        "f0_natural": f0_natural,
        "note_events": note_events,
        "config": config,
        "source": "notes_fallback_naturalized" if bool(config.get("naturalize", True)) else "notes_fallback",
    }


def _assemble_concat(segment_paths: list[Path], output_wav: Path, sample_rate: int, normalize: bool) -> float:
    import numpy as np
    from utils.audio import save_wav

    parts = []
    for path in segment_paths:
        wav, sr = _read_wav(path)
        if sr != sample_rate:
            raise ValueError(f"Segment sample rate mismatch: {path} has {sr}, expected {sample_rate}")
        parts.append(_to_mono(wav))
    full = np.concatenate(parts) if parts else np.zeros(0, dtype="float32")
    save_wav(full, str(output_wav), sample_rate, norm=bool(normalize))
    return len(full) / float(sample_rate)


def _assemble_timeline(items: list[dict], segment_paths: list[Path], output_wav: Path, sample_rate: int, normalize: bool) -> float:
    import numpy as np
    from utils.audio import save_wav

    end_time = 0.0
    for item in items:
        try:
            end_time = max(end_time, float(item.get("end", 0.0) or 0.0))
        except (TypeError, ValueError):
            pass
    if end_time <= 0.0:
        return _assemble_concat(segment_paths, output_wav, sample_rate, normalize)

    full = np.zeros(max(1, int(round(end_time * sample_rate))), dtype="float32")
    for item, path in zip(items, segment_paths):
        wav, sr = _read_wav(path)
        if sr != sample_rate:
            raise ValueError(f"Segment sample rate mismatch: {path} has {sr}, expected {sample_rate}")
        wav = _to_mono(wav)
        try:
            start_time = float(item.get("start", 0.0) or 0.0)
        except (TypeError, ValueError):
            start_time = 0.0
        start = max(0, int(round(start_time * sample_rate)))
        end = start + len(wav)
        if end > len(full):
            full = np.pad(full, (0, end - len(full)))
        full[start:end] += wav

    peak = float(np.max(np.abs(full))) if len(full) else 0.0
    if peak > 1.0:
        full = full / peak
    save_wav(full, str(output_wav), sample_rate, norm=bool(normalize))
    return len(full) / float(sample_rate)


def _array_stats(array) -> dict:
    import numpy as np

    arr = np.asarray(array)
    has_nan = bool(np.isnan(arr).any()) if arr.size else False
    has_inf = bool(np.isinf(arr).any()) if arr.size else False
    finite = arr[np.isfinite(arr)]
    if finite.size:
        return {
            "min": float(finite.min()),
            "max": float(finite.max()),
            "mean": float(finite.mean()),
            "std": float(finite.std()),
            "has_nan": has_nan,
            "has_inf": has_inf,
            "shape": list(arr.shape),
        }
    return {
        "min": None,
        "max": None,
        "mean": None,
        "std": None,
        "has_nan": has_nan,
        "has_inf": has_inf,
        "shape": list(arr.shape),
    }


def _to_numpy(value):
    if value is None:
        return None
    if hasattr(value, "detach"):
        value = value.detach().cpu()
    if hasattr(value, "numpy"):
        return value.numpy()
    return value


def _save_mel_diagnostics(item_name: str, mel_out, f0_pred, diagnostic_dir: Path, f0_source: str, fallback_info: dict | None = None) -> dict:
    import numpy as np

    diagnostic_dir.mkdir(parents=True, exist_ok=True)
    safe_name = "".join(ch if ch.isalnum() or ch in {"-", "_"} else "_" for ch in item_name)
    mel_path = diagnostic_dir / f"{safe_name}.mel.npy"
    stats_path = diagnostic_dir / f"{safe_name}.mel_stats.json"
    f0_raw_path = diagnostic_dir / f"{safe_name}.f0_raw.npy"
    f0_natural_path = diagnostic_dir / f"{safe_name}.f0_natural.npy"

    mel_np = np.asarray(_to_numpy(mel_out), dtype=np.float32)
    np.save(str(mel_path), mel_np)

    f0_np = _to_numpy(f0_pred)
    f0_exists = f0_np is not None
    mel_stats = _array_stats(mel_np)
    f0_stats = _array_stats(f0_np) if f0_exists else None
    f0_raw = fallback_info.get("f0_raw") if fallback_info else None
    f0_natural = fallback_info.get("f0_natural") if fallback_info else None
    if f0_raw is not None:
        np.save(str(f0_raw_path), np.asarray(f0_raw, dtype=np.float32))
    if f0_natural is not None:
        np.save(str(f0_natural_path), np.asarray(f0_natural, dtype=np.float32))
    f0_raw_stats = _array_stats(f0_raw) if f0_raw is not None else None
    f0_natural_stats = _array_stats(f0_natural) if f0_natural is not None else None
    fallback_config = fallback_info.get("config", {}) if fallback_info else {}
    stats = {
        "item_name": item_name,
        "mel_npy": str(mel_path),
        "mel_min": mel_stats["min"],
        "mel_max": mel_stats["max"],
        "mel_mean": mel_stats["mean"],
        "mel_std": mel_stats["std"],
        "mel_has_nan": mel_stats["has_nan"],
        "mel_has_inf": mel_stats["has_inf"],
        "mel_shape": mel_stats["shape"],
        "mel": mel_stats,
        "f0_exists": bool(f0_exists),
        "f0_source": f0_source,
        "f0_naturalized": bool(fallback_info and f0_source == "notes_fallback_naturalized"),
        "f0_raw_npy": str(f0_raw_path) if f0_raw is not None else None,
        "f0_natural_npy": str(f0_natural_path) if f0_natural is not None else None,
        "f0_raw_min": f0_raw_stats["min"] if f0_raw_stats else None,
        "f0_raw_max": f0_raw_stats["max"] if f0_raw_stats else None,
        "f0_raw_mean": f0_raw_stats["mean"] if f0_raw_stats else None,
        "f0_raw_std": f0_raw_stats["std"] if f0_raw_stats else None,
        "f0_raw_has_nan": f0_raw_stats["has_nan"] if f0_raw_stats else None,
        "f0_raw_has_inf": f0_raw_stats["has_inf"] if f0_raw_stats else None,
        "f0_natural_min": f0_natural_stats["min"] if f0_natural_stats else None,
        "f0_natural_max": f0_natural_stats["max"] if f0_natural_stats else None,
        "f0_natural_mean": f0_natural_stats["mean"] if f0_natural_stats else None,
        "f0_natural_std": f0_natural_stats["std"] if f0_natural_stats else None,
        "f0_natural_has_nan": f0_natural_stats["has_nan"] if f0_natural_stats else None,
        "f0_natural_has_inf": f0_natural_stats["has_inf"] if f0_natural_stats else None,
        "f0_min": f0_stats["min"] if f0_stats else None,
        "f0_max": f0_stats["max"] if f0_stats else None,
        "f0_mean": f0_stats["mean"] if f0_stats else None,
        "f0_std": f0_stats["std"] if f0_stats else None,
        "f0_has_nan": f0_stats["has_nan"] if f0_stats else None,
        "f0_has_inf": f0_stats["has_inf"] if f0_stats else None,
        "f0_shape": f0_stats["shape"] if f0_stats else None,
        "f0": f0_stats,
        "vibrato_enabled": bool(fallback_config.get("vibrato_enabled", False)),
        "transition_smoothing_ms": fallback_config.get("transition_ms"),
        "vibrato_rate_hz": fallback_config.get("vibrato_rate_hz"),
        "vibrato_depth_cents": fallback_config.get("vibrato_depth_cents"),
        "tail_fall_cents": fallback_config.get("tail_fall_cents"),
        "jitter_cents": fallback_config.get("jitter_cents"),
    }
    stats_path.write_text(json.dumps(stats, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    stats["mel_stats_json"] = str(stats_path)
    return stats


def _infer_once_with_diagnostics(infer, payload: dict, item_name: str, diagnostic_dir: Path, hparams: dict, f0_fallback_config: dict):
    import torch

    item = infer.preprocess_input(payload, input_type=payload["input_type"] if payload.get("input_type") else "word")
    if item is None:
        raise RuntimeError(f"DiffSinger preprocessing returned None for {item_name}.")

    sample = infer.input_to_batch(item)
    txt_tokens = sample["txt_tokens"]
    spk_id = sample.get("spk_ids")
    with torch.no_grad():
        output = infer.model(
            txt_tokens,
            spk_id=spk_id,
            ref_mels=None,
            infer=True,
            pitch_midi=sample["pitch_midi"],
            midi_dur=sample["midi_dur"],
            is_slur=sample["is_slur"],
        )
        mel_out = output["mel_out"]
        f0_source = "none"
        fallback_info = None
        if hparams.get("pe_enable") is not None and hparams.get("pe_enable") and hasattr(infer, "pe"):
            f0_pred = infer.pe(mel_out).get("f0_denorm_pred", None)
            if f0_pred is not None:
                f0_source = "pitch_extractor"
        else:
            f0_pred = output.get("f0_denorm", None)
            if f0_pred is not None:
                f0_source = "acoustic_output"
            else:
                f0_pred = output.get("f0", None)
                if f0_pred is not None:
                    f0_source = "acoustic_output"

        if f0_pred is None and str(payload.get("input_type") or "word").strip().lower() == "word":
            f0_pred, fallback_info = _build_f0_from_payload_notes(payload, mel_out, hparams, f0_fallback_config)
            if fallback_info is not None:
                f0_source = fallback_info.get("source", "notes_fallback")

        if f0_pred is None and bool(hparams.get("use_nsf")):
            raise RuntimeError(
                f"Vocoder use_nsf is true but no f0 is available for {item_name}. "
                "Expected acoustic f0 or notes_fallback f0."
            )

        diagnostics = _save_mel_diagnostics(item_name, mel_out, f0_pred, diagnostic_dir, f0_source, fallback_info)
        if f0_pred is not None:
            wav_out = infer.run_vocoder(mel_out, f0=f0_pred)
        else:
            wav_out = infer.run_vocoder(mel_out)

    wav_out = wav_out.cpu().numpy()
    return wav_out[0], diagnostics


def main() -> None:
    args = parse_args()
    diffsinger_root = Path(args.diffsinger_root).resolve()
    if not diffsinger_root.exists():
        raise FileNotFoundError(f"DiffSinger source root does not exist: {diffsinger_root}")

    input_json = Path(args.input_json).resolve()
    output_wav = Path(args.output_wav).resolve()
    if not input_json.exists():
        raise FileNotFoundError(f"DiffSinger input JSON does not exist: {input_json}")

    payloads, input_format = _load_payloads(input_json)
    selected_payloads = _select_payloads(payloads, args.start_phrase, args.max_phrases)
    if not selected_payloads:
        raise ValueError(
            f"No DiffSinger inputs selected from {input_json}; "
            f"start_phrase={args.start_phrase}, max_phrases={args.max_phrases}."
        )
    for index, payload in enumerate(selected_payloads, start=1):
        _validate_payload(payload, index)

    _patch_numpy_aliases()
    _patch_yaml_open_encoding()
    _patch_scipy_signal_aliases()
    _install_optional_training_stubs()
    if _has_word_level_payload(selected_payloads):
        _ensure_real_pypinyin_available()
    else:
        _install_pypinyin_stub()
    os.chdir(diffsinger_root)
    sys.path.insert(0, str(diffsinger_root))
    _install_diffsinger_task_stub()

    from utils.audio import save_wav
    from utils.hparams import hparams, set_hparams

    config_path = Path(args.config)
    if config_path.is_absolute():
        config_arg = str(config_path)
    else:
        config_arg = str(config_path).replace("\\", "/")

    set_hparams(
        config=config_arg,
        exp_name=args.exp_name,
        hparams_str=args.hparams,
        print_hparams=True,
    )

    infer_class_used = (args.infer_class or "cascade").lower().strip()
    infer_class_auto_switched = False
    infer_class_switch_reason = ""
    if infer_class_used not in {"cascade", "ds_cascade", "diffsinger_cascade"}:
        raise ValueError("This OpenCpop DiffSinger pipeline is fixed to cascade inference. Use --infer-class cascade.")

    fs2_ckpt = str(hparams.get("fs2_ckpt", "") or "").strip()
    pretrain_fs_ckpt = str(hparams.get("pretrain_fs_ckpt", "") or "").strip()
    if not fs2_ckpt and not pretrain_fs_ckpt:
        raise RuntimeError(
            "Cascade inference requires fs2_ckpt or pretrain_fs_ckpt. "
            "Stage variance/FS checkpoint first and set acoustic config "
            "fs2_ckpt=checkpoints/<variance_runtime_exp>."
        )
    print(f"| cascade fs2_ckpt: {fs2_ckpt or pretrain_fs_ckpt}")

    infer_cls = _load_infer_class(infer_class_used)
    device = None if args.device == "auto" else args.device
    infer = infer_cls(hparams, device=device)
    f0_fallback_config = _load_f0_fallback_config(args.f0_fallback_config)

    output_wav.parent.mkdir(parents=True, exist_ok=True)
    segment_dir = Path(args.segments_dir).resolve() if args.segments_dir else output_wav.parent / "segments"
    segment_dir.mkdir(parents=True, exist_ok=True)

    segment_reports = []
    segment_paths: list[Path] = []
    sample_rate = int(hparams["audio_sample_rate"])
    for index, payload in enumerate(selected_payloads, start=1):
        item_name = str(payload.get("item_name") or f"phrase_{index:03d}")
        safe_name = "".join(ch if ch.isalnum() or ch in {"-", "_"} else "_" for ch in item_name)
        segment_wav = segment_dir / f"{safe_name}.wav"
        wav, diagnostics = _infer_once_with_diagnostics(infer, payload, item_name, segment_dir, hparams, f0_fallback_config)
        if wav is None:
            raise RuntimeError(f"DiffSinger inference returned None for {item_name}.")
        save_wav(wav, str(segment_wav), sample_rate, norm=False)
        segment_paths.append(segment_wav)
        segment_report = _segment_report(payload, item_name, segment_wav)
        segment_report["mel_npy"] = diagnostics.get("mel_npy")
        segment_report["mel_stats_json"] = diagnostics.get("mel_stats_json")
        segment_report["mel_stats"] = diagnostics.get("mel")
        segment_report["f0_exists"] = diagnostics.get("f0_exists")
        segment_report["f0_source"] = diagnostics.get("f0_source")
        segment_report["f0_naturalized"] = diagnostics.get("f0_naturalized")
        segment_report["f0_raw_npy"] = diagnostics.get("f0_raw_npy")
        segment_report["f0_natural_npy"] = diagnostics.get("f0_natural_npy")
        segment_report["f0_stats"] = diagnostics.get("f0")
        segment_reports.append(segment_report)
        _cleanup_cuda()

    assembly_mode = args.assembly_mode
    if input_format == "diffsinger_input":
        assembly_mode = "concat"
    if assembly_mode == "timeline":
        duration_sec = _assemble_timeline(selected_payloads, segment_paths, output_wav, sample_rate, bool(args.normalize))
    else:
        duration_sec = _assemble_concat(segment_paths, output_wav, sample_rate, bool(args.normalize))

    report = {
        "status": "success",
        "output_wav": str(output_wav),
        "sample_rate": sample_rate,
        "infer_class_requested": args.infer_class,
        "infer_class": infer_class_used,
        "infer_class_auto_switched": infer_class_auto_switched,
        "infer_class_switch_reason": infer_class_switch_reason,
        "exp_name": args.exp_name,
        "hparams_summary": {
            "base_config": hparams.get("base_config"),
            "work_dir": hparams.get("work_dir"),
            "fs2_ckpt": hparams.get("fs2_ckpt"),
            "pretrain_fs_ckpt": hparams.get("pretrain_fs_ckpt"),
            "vocoder_ckpt": hparams.get("vocoder_ckpt"),
            "pe_enable": hparams.get("pe_enable"),
            "use_nsf": hparams.get("use_nsf"),
            "audio_sample_rate": hparams.get("audio_sample_rate"),
            "hop_size": hparams.get("hop_size"),
        },
        "input_json": str(input_json),
        "input_format": input_format,
        "selected_input_types": sorted({str(payload.get("input_type") or "word").lower() for payload in selected_payloads}),
        "f0_fallback_config": f0_fallback_config,
        "phrase_count_total": len(payloads),
        "phrase_count_inferred": len(selected_payloads),
        "start_phrase": args.start_phrase,
        "max_phrases": args.max_phrases,
        "assembly_mode": assembly_mode,
        "normalize_output": bool(args.normalize),
        "duration_sec": duration_sec,
        "segments_dir": str(segment_dir),
        "segments": segment_reports,
    }
    print(json.dumps(report, ensure_ascii=False))


def _segment_report(payload: dict, item_name: str, segment_wav: Path) -> dict:
    input_type = str(payload.get("input_type") or "word").strip().lower()
    report = {
        "item_name": item_name,
        "phrase_id": payload.get("phrase_id"),
        "input_type": input_type,
        "start": payload.get("start"),
        "end": payload.get("end"),
        "output_wav": str(segment_wav),
        "normalized": False,
    }
    if input_type == "word":
        report["word_count"] = len(str(payload.get("text", "")).replace("AP", "A").replace("SP", "S"))
        report["note_group_count"] = len([part for part in str(payload.get("notes", "")).split("|") if part.strip()])
    else:
        report["phoneme_count"] = len(str(payload.get("ph_seq", "")).split())
    return report


if __name__ == "__main__":
    main()
