from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


def _patch_numpy_aliases() -> None:
    try:
        import numpy as np
    except ImportError:
        return
    for name, value in {
        "int": int,
        "float": float,
        "bool": bool,
        "complex": complex,
        "object": object,
    }.items():
        if not hasattr(np, name):
            setattr(np, name, value)


def _patch_yaml_open_encoding() -> None:
    import builtins

    original_open = builtins.open

    def open_with_utf8_yaml(file, mode="r", buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None):
        if encoding is None and "b" not in mode:
            path_text = os.fspath(file) if isinstance(file, (str, os.PathLike)) else ""
            if path_text.lower().endswith((".yaml", ".yml")):
                encoding = "utf-8"
        return original_open(file, mode, buffering, encoding, errors, newline, closefd, opener)

    builtins.open = open_with_utf8_yaml


def _patch_scipy_signal_aliases() -> None:
    try:
        import scipy.signal as signal
        from scipy.signal import windows
    except ImportError:
        return
    if not hasattr(signal, "kaiser") and hasattr(windows, "kaiser"):
        signal.kaiser = windows.kaiser


def _install_optional_training_stubs() -> None:
    try:
        import webrtcvad  # noqa: F401
        return
    except ImportError:
        pass

    import types

    module = types.ModuleType("webrtcvad")

    class _Vad:
        def __init__(self, *_args, **_kwargs):
            raise RuntimeError("webrtcvad is not installed; VAD trimming is unavailable during training/data preparation.")

    module.Vad = _Vad
    sys.modules["webrtcvad"] = module


def _install_pypinyin_stub() -> None:
    try:
        import pypinyin  # noqa: F401
        return
    except ImportError:
        pass

    import types

    module = types.ModuleType("pypinyin")

    class _Style:
        NORMAL = 0
        TONE3 = 8

    def _missing_pypinyin(*_args, **_kwargs):
        raise RuntimeError(
            "pypinyin is not installed. Word-level DiffSinger input is unavailable, "
            "but phoneme-level OpenCpop input does not require it."
        )

    module.Style = _Style
    module.lazy_pinyin = _missing_pypinyin
    module.pinyin = _missing_pypinyin
    sys.modules["pypinyin"] = module


def _install_diffsinger_task_stub() -> None:
    if "usr.diffsinger_task" in sys.modules:
        return

    import types
    from usr.diff.candidate_decoder import FFT
    from usr.diff.net import DiffNet

    module = types.ModuleType("usr.diffsinger_task")
    module.DIFF_DECODERS = {
        "wavenet": lambda hp: DiffNet(hp["audio_num_mel_bins"]),
        "fft": lambda hp: FFT(hp["hidden_size"], hp["dec_layers"], hp["dec_ffn_kernel_size"], hp["num_heads"]),
    }
    sys.modules["usr.diffsinger_task"] = module


def _load_infer_class(name: str):
    value = name.lower().strip()
    if value in {"e2e", "ds_e2e", "diffsinger_e2e"}:
        from inference.svs.ds_e2e import DiffSingerE2EInfer
        return DiffSingerE2EInfer
    if value in {"cascade", "ds_cascade", "diffsinger_cascade"}:
        from inference.svs.ds_cascade import DiffSingerCascadeInfer
        return DiffSingerCascadeInfer
    raise ValueError(f"Unsupported DiffSinger infer class: {name}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run DiffSinger OpenCpop inference from a phoneme-level JSON input.")
    parser.add_argument("--diffsinger-root", required=True, help="Path to external DiffSinger source root.")
    parser.add_argument("--config", required=True, help="DiffSinger config YAML path, relative to DiffSinger root or absolute.")
    parser.add_argument("--exp-name", required=True, help="DiffSinger checkpoint experiment name under checkpoints/.")
    parser.add_argument("--input-json", required=True, help="Input JSON generated by src.svs.diffsinger_opencpop_exporter.")
    parser.add_argument("--output-wav", required=True, help="Destination wav path.")
    parser.add_argument("--infer-class", default="e2e", help="e2e or cascade.")
    parser.add_argument("--device", default="auto", help="auto, cpu, cuda, or cuda:N.")
    parser.add_argument("--hparams", default="", help="Optional comma-separated DiffSinger hparams overrides.")
    parser.add_argument("--normalize", action="store_true", help="Peak-normalize saved wav.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    diffsinger_root = Path(args.diffsinger_root).resolve()
    if not diffsinger_root.exists():
        raise FileNotFoundError(f"DiffSinger source root does not exist: {diffsinger_root}")

    input_json = Path(args.input_json).resolve()
    output_wav = Path(args.output_wav).resolve()
    if not input_json.exists():
        raise FileNotFoundError(f"DiffSinger input JSON does not exist: {input_json}")

    _patch_numpy_aliases()
    _patch_yaml_open_encoding()
    _patch_scipy_signal_aliases()
    _install_optional_training_stubs()
    _install_pypinyin_stub()
    os.chdir(diffsinger_root)
    sys.path.insert(0, str(diffsinger_root))
    _install_diffsinger_task_stub()

    from utils.audio import save_wav
    from utils.hparams import hparams, set_hparams

    config_path = Path(args.config)
    if config_path.is_absolute():
        config_arg = str(config_path)
    else:
        config_arg = str(config_path).replace("\\", "/")

    set_hparams(
        config=config_arg,
        exp_name=args.exp_name,
        hparams_str=args.hparams,
        print_hparams=True,
    )

    payload = json.loads(input_json.read_text(encoding="utf-8"))
    required = ["text", "ph_seq", "note_seq", "note_dur_seq", "is_slur_seq", "input_type"]
    missing = [key for key in required if not payload.get(key)]
    if missing:
        raise ValueError(f"DiffSinger input JSON missing required fields: {missing}")

    infer_cls = _load_infer_class(args.infer_class)
    device = None if args.device == "auto" else args.device
    infer = infer_cls(hparams, device=device)
    wav = infer.infer_once(payload)
    if wav is None:
        raise RuntimeError("DiffSinger inference returned None.")

    output_wav.parent.mkdir(parents=True, exist_ok=True)
    save_wav(wav, str(output_wav), hparams["audio_sample_rate"], norm=bool(args.normalize))

    report = {
        "status": "success",
        "output_wav": str(output_wav),
        "sample_rate": hparams["audio_sample_rate"],
        "infer_class": args.infer_class,
        "exp_name": args.exp_name,
        "input_json": str(input_json),
    }
    print(json.dumps(report, ensure_ascii=False))


if __name__ == "__main__":
    main()