from __future__ import annotations

from pathlib import Path
from typing import Iterable


DATA_DIRS = [
    "data/raw",
    "data/score",
    "data/lyrics",
    "data/phoneme",
    "data/alignment",
    "data/svs",
    "outputs/logs",
]


def project_root(config: dict) -> Path:
    """Return the project root stored in config.

    Input:
        config: Pipeline config loaded by app.py.
    Output:
        Absolute project root path.
    TODO:
        Support separate workspace and artifact roots for larger experiments.
    """
    return Path(config.get("_project_root", ".")).resolve()


def resolve_path(config: dict, path_value: str | Path) -> Path:
    """Resolve a project-relative or absolute path.

    Input:
        config: Pipeline config containing _project_root.
        path_value: Relative or absolute path string.
    Output:
        Absolute pathlib.Path.
    TODO:
        Add path validation for remote storage backends.
    """
    path = Path(path_value)
    if path.is_absolute():
        return path
    return project_root(config) / path


def path_from_config(config: dict, key: str) -> Path:
    """Resolve a named path from the config paths section.

    Input:
        config: Pipeline config.
        key: Key under config["paths"].
    Output:
        Absolute pathlib.Path for that configured path.
    TODO:
        Add typed config validation before pipeline execution.
    """
    return resolve_path(config, config["paths"][key])


def ensure_parent(path: Path) -> None:
    """Create the parent directory for a file path.

    Input:
        path: File path whose parent should exist.
    Output:
        None.
    TODO:
        Add optional permission checks for shared lab machines.
    """
    path.parent.mkdir(parents=True, exist_ok=True)


def ensure_directories(config: dict, extra_dirs: Iterable[str] | None = None) -> None:
    """Create all standard project data and output directories.

    Input:
        config: Pipeline config.
        extra_dirs: Optional additional project-relative directories.
    Output:
        None.
    TODO:
        Generate a manifest of created directories for reproducible runs.
    """
    root = project_root(config)
    for directory in [*DATA_DIRS, *(extra_dirs or [])]:
        (root / directory).mkdir(parents=True, exist_ok=True)


def should_write(path: Path, config: dict) -> bool:
    """Return whether a file may be written.

    Input:
        path: Output path.
        config: Pipeline config containing pipeline.overwrite.
    Output:
        True when the file does not exist or overwrite is enabled.
    TODO:
        Support stage-level overwrite policies.
    """
    overwrite = config.get("pipeline", {}).get("overwrite", True)
    return overwrite or not path.exists()


def allow_mock(config: dict) -> bool:
    """Return whether mock outputs are allowed.

    Input:
        config: Pipeline config.
    Output:
        Boolean allow_mock_outputs flag.
    TODO:
        Replace with a stricter execution mode enum.
    """
    return bool(config.get("pipeline", {}).get("allow_mock_outputs", True))


def require_or_mock_input(path: Path, config: dict, description: str) -> str:
    """Check an input path and return an execution status.

    Input:
        path: Expected input file.
        config: Pipeline config with allow_mock_outputs.
        description: Human-readable input description for error messages.
    Output:
        "success" if the file exists, otherwise "mock" if mocks are allowed.
    TODO:
        Add content validation, not just file existence checks.
    """
    if path.exists():
        return "success"
    if allow_mock(config):
        return "mock"
    raise FileNotFoundError(f"Missing required {description}: {path}")


def write_text(path: Path, content: str, config: dict) -> None:
    """Write UTF-8 text when overwrite policy allows it.

    Input:
        path: Destination file.
        content: Text content.
        config: Pipeline config.
    Output:
        None.
    TODO:
        Add atomic writes for long-running experiments.
    """
    if not should_write(path, config):
        return
    ensure_parent(path)
    path.write_text(content, encoding="utf-8")


def write_placeholder(path: Path, label: str, config: dict) -> None:
    """Write a small placeholder file for mock pipeline execution.

    Input:
        path: Destination path.
        label: Description of the placeholder artifact.
        config: Pipeline config.
    Output:
        None.
    TODO:
        Replace text placeholders with valid media files when needed by tools.
    """
    content = f"PLACEHOLDER: {label}\nThis file was generated by the mock pipeline.\n"
    write_text(path, content, config)
